server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      start-saga: start-saga
      orchestrator: orchestrator
      finish-success: finish-success
      finish-fail: finish-fail

    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

services:
  usuario:
    url: ${USUARIO_SERVICE_URL:http://usuario-service:3000}
  agendamento:
    url: ${AGENDAMENTO_SERVICE_URL:http://agendamento-service:3000}
  hospital:
    url: ${HOSPITAL_SERVICE_URL:http://hospital-service:3000}

logging:
  level:
    org:
      apache:
        kafka: OFF
