server:
  port: 3000
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %Dms'
      directory: logs
      prefix: access_log
      suffix: .log

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      usuario-success: usuario-success
      usuario-fail: usuario-fail
    consumer:
      group-id: usuario-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/usuarios}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    clean-disabled: false

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

jwt:
  secret: ${JWT_SECRET:minha-chave-secreta-super-segura-para-jwt-token-123456789}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 horas em ms
  expiration-time: ${JWT_EXPIRATION_TIME:86400000}  # 24 horas em ms
