server:
  port: 3002

spring:
  application:
    name: api-gateway-service
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      comeca-saga: comeca-saga
      notifica-fim: notifica-fim
    consumer:
      group-id: appointment-group
      auto-offset-reset: latest

# Configuração JWT
jwt:
  secret: ${JWT_SECRET:mySecretKeyForHospitalGatewayService}
  expiration: ${JWT_EXPIRATION:86400}

# URL do orchestrator-service (único ponto de comunicação)
orchestrator-service:
  url: ${ORCHESTRATOR_SERVICE_URL:http://orchestrator-service:8080}

services:
  orchestrator-service:
    url: ${ORCHESTRATOR_SERVICE_URL:http://orchestrator-service:8080}

logging:
  level:
    "[org.apache.kafka]": INFO
    "[com.fiap.techchallenge.appointment_service]": DEBUG

# Configuração do Feign Client (mantido para comunicação com orchestrator)
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Resilience4j configuration for orchestrator calls
resilience4j:
  retry:
    instances:
      orchestrator-find:
        max-attempts: 3
        wait-duration: 200ms
      orchestrator-validate:
        max-attempts: 3
        wait-duration: 200ms

  circuitbreaker:
    instances:
      orchestrator-find:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
      orchestrator-validate:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
